# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

# Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire', '~> 4.2.0'
  pod 'KRProgressHUD'
  pod 'Alertift', '~> 3.0'
  pod 'Alamofire-Synchronous', '~> 4.0'
  pod 'ReachabilitySwift'
  pod 'OnboardingKit'
  pod 'expanding-collection', '~> 1.0.3'
  pod 'SwiftMessages'
  #pod 'Former'
  pod 'Firebase/Auth'
  pod 'MMTabBarAnimation'


target 'SnapGyft' do
   
end


target 'SnapGyftMerchant’ do
 
end

